baseURL = 'https://sarvnazale.com/'
languageCode = 'en-us'
title = 'sarvnazale'
theme = 'PaperMod'
enableEmoji = true

[Menu]
 [[menu.Main]]
  identifier = "about"
  name = "about"
  url = "/about"
  weight = 1
 [[menu.Main]]
  identifier = "portfolio"
  name = "portfolio"
  url = "/Portfolio"
  weight = 2
 [[menu.Main]]
  identifier = "experiences"
  name = "experiences"
  url = "/Experiences"
  weight = 3
 [[menu.Main]]
  identifier = "fun stuff!"
  name = "fun stuff"
  url = "/Fun_Stuff"
  weight = 4


[params]
defaultTheme = "dark"
# favicon 
favicon = "img/favicon/favicon.ico"
hideMeta = true

[params.homeInfoParams]
Title = "Hi!! ! ! ! ! ! ‚ù§Ô∏è üëã"
#Content = "My name is Sarvnaz, and this is my personal website."
Content = """
My name is Sarvnaz, welcome to my personal website. 
- I keep track of my portfolio and experiences here, as well as some fun projects that I am up to.
- See my resume [here](https://sarvnazale.com/resume.pdf) and my transcript [here](https://sarvnazale.com/transcript.pdf).
- Please reach out if you'd like to chat! ‚òï
"""
[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/sarvnaz-ale/"


[[params.socialIcons]]
name = "Github"
url = "https://github.com/sarvnazale"

[[params.socialIcons]]
name = "email"
url = "mailto:hello@sarvnazale.com"

[params.meta]
 favicon=true

[params.assets]
    favicon = "img/favicon/favicon.ico"
    favicon16x16 = "img/favicon/favicon-16x16.png"
    favicon32x32 = "img/favicon/favicon-32x32.png"
    apple_touch_icon = "img/favicon/apple-touch-icon.png"

